sonar.projectKey=Becker-leopoldo_Physio-Notes
sonar.organization=Becker-leopoldo
sonar.projectName=Physio-Notes
sonar.projectVersion=0.287
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=false

sonar.sources=backend,frontend
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**

sonar.python.version=3.11

# Cobertura de testes (opcional)
# sonar.python.coverage.reportPaths=coverage.xml
